image: node:10.15.3
# Cache modules in between jobs
cache:
  paths:
  - node_modules/

stages:
- build
- test
- deploy

before_script:
 - npm install

compile:
  stage: build
  script:
   - npm run build

test:
  stage: test
  script:
   - npm test

deply-staging:
  stage: deploy
  script:
    - echo 'Deploy Development'
  only: ['development']

deply-master:
  stage: deploy
  script:
    - echo 'Deploy Master'
  only: ['master']
