image: node:10.15.3
# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
- build
- test

before_script:
 - npm install

compile:
  stage: build
  script:
   - npm run build

test:
  stage: test
  script:
   - npm test
