module.exports = {
    REGISTER:'REGISTER',
    LOGIN:'LOGIN',
    LOGOUT:'LOGOUT',
    ADD_TO_CART:'ADD_TO_CART',
    INCREMENT_QTY:'INCREMENT_QTY',
    DECREMENT_QTY:'DECREMENT_QTY',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    CHECKOUT:'CHECKOUT'
}