module.exports = {
    GET_USERS:'GET_USERS',
    ADD_USER:'ADD_USER',
    UPDATE_USER:'UPDATE_USER',
    DELETE_USER:'DELETE_USER',
    GET_TRANSACTIONS:'GET_TRANSACTIONS',
    REQUEST_DATA:'REQUEST_DATA',
    REQUEST_TRANSACTIONS:'REQUEST_TRANSACTIONS',
    INVALIDATE_DATA:'INVALIDATE_DATA',
}